name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - add_gh_pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: WEBPAGE/

    steps:
      - name: Checkout REpo
        uses: actions/checkout@v4

      - name: Setup NOde
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: List build output
        run: ls -l dist

      - name: Add 404.html fallback
        run: cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: WEBPAGE/dist/
