name: "Scrape Parkleitsystem Gießen"
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  scrape_and_save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4

      - name: Setup Python3 & Install depencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraping script and save data
        run: |
          parkhouse_data=$(python3 scraping_parkleitsystem.py)
          filename="$(echo "$parkhouse_data" | jq -r .timestamp).json"
          mkdir -p data
          touch data/$filename
          echo $parkhouse_data > "data/$filename"

      - name: Configure git
        run: |
          git config user.name ${{ secrets.GIT_USERNAME }}

      - name: Check if the branch exists
        id: branch_check
        run: |
          git fetch origin
          if git show-ref --quiet refs/remotes/origin/parkleitsystem-collection; then
            echo "Branch exists"
            echo "::set-output name=branch_exists::true"
          else
            echo "Branch does not exist"
            echo "::set-output name=branch_exists::false"
          fi

      - name: Create or checkout branch
        if: steps.branch_check.outputs.branch_exists == 'false'
        run: git checkout -b parkleitsystem-collection

      - if: steps.branch_check.outputs.branch_exists == 'true'
        run: git checkout parkleitsystem-collection

      - name: Push changes to parkleitsystem-collection
        run: |
          git add .
          git commit -m 'Adding new parkhouse data'
          git push origin parkleitsystem-collection
